name: Generate Pydoc HTML

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ AIXÒ DONA PERMISOS AL BOT PER FER PUSH

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate HTML docs with pydoc
      run: |
        mkdir -p docs
        python -m pydoc -w blog
        mv blog.html docs/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
