name: Django Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

    steps:
      - name: Clona el repositori
        uses: actions/checkout@v3

      - name: Instal·la Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instal·la les dependències
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executa les migracions
        run: |
          python manage.py migrate

      - name: Executa els tests unitaris
        run: |
          python manage.py test
